version: 0.0.1
dbFile: .mockapi.db.json
dbDataPath: /
apiRoutePrefix: /api/cinetpay
routes:
  get:
    - /transfer/check/money
    - /finalizepayment
    - /finalizepayment/5df64dd9c5447739327eb88e1e4ea0ac015555cc262ea308c91acbd4e5c8fb95f4bd0bd7cad877a452f877fa6f51fe74184d00a84ab7f9
  post:
    - path: /auth/login
      restrictedBody: true
      bodyFields:
        apikey: true
        password: true
    - path: /transfer/contact
      restrictedBody: true
      bodyFields:
        data: true
    - path: /transfer/money/send/contact
      restrictedBody: true
      bodyFields:
        data: true
        notify_url: true
      scheduleNotification:
        followProp: notify_url
        timeoutInSecond: 120
        notificationMethod: POST
        postDataPath: /notifications/cash_out
    - path: /payment
      restrictedBody: true
      bodyFields:
        apikey: true
        site_id: true
        transaction_id: true
        amount: true
        currency: true
        description: true
        notify_url: true
        return_url: true
        channels: true
        lang: true
        metadata: true
      scheduleNotification:
        followProp: notify_url
        timeoutInSecond: 120
        notificationMethod: POST
        postDataPath: /notifications/cash_in
    - path: /payment/check
      restrictedBody: true
      bodyFields:
        apikey: true
        site_id: true
        transaction_id: true




      
