version: 0.0.1
dbFile: .mockapi.db.json
dbDataPath: /
apiRoutePrefix: /api/cinetpay
routes:
  get:
  post:
    - path: /auth/login
      restrictedBody: true
      bodyFields:
        apikey: true
        password: true
    - path: /transfer/contact
      restrictedBody: true
      bodyFields:
        prefix: true
        phone: true
        name: true
        surname: true
        email: true